/**
 * 
 */
package com.bhuwan.java.basics.projecteuler;

/**
 * @author bhuwangautam
 *
 */
public class EvenFibonacci {

	public static void main(String[] args) {
		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous
		 * two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * 
		 * By considering the terms in the Fibonacci sequence whose values do not exceed
		 * four million, find the sum of the even-valued terms.
		 */

		int finonacci = 0;
		int a = 0;
		int b = 1;
		int sum = 0;
		while (finonacci < 4000000) {
			finonacci = a + b; // fib=5
			if (finonacci % 2 == 0)
				sum += finonacci;  //sum = 2
			a = b; //a = 2
			b = finonacci; //b = 3

		}
		System.out.println("sum: " + sum);
	}
}
